import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useRef } from 'react';

import { IDataProgramationLink } from './api/programation-link';

async function crawlDataFromJW(date: Date) {
  const resLink = await fetch(`http://localhost:3000/api/programation-link?date=${date}`);
  const dataLink: IDataProgramationLink = await resLink.json();

  const resData = await fetch(`http://localhost:3000/api/programation-data?url=${dataLink.link}`);
  const dataProgamation = await resData.json();

  return dataProgamation.html;
};

const Home: NextPage = () => {
  const $div: any = useRef(null);
  const selectedDate = new Date();

  useEffect(() => {
    crawlDataFromJW(selectedDate).then(d => $div.current.innerHTML = d)
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div ref={$div}></div>
    </div>
  )
}

export default Home;
